from fyers_apiv3 import fyersModel

client_id = "IDHL0651SW-100"
access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIl0sImF0X2hhc2giOiJnQUFBQUFCcVhTRWI3dG1wSm44SmNjcDV6WlZ5WTQ4cDlXSzEwVE92THRseDRDcXlHNWlrN0RLWUFyUHdmdGpjMjlDeFE2elhBS2lWeFlfdDljODlFUWljZHl0b2ljUEhBSG45MXhOUDJ2SFdSXzBud2p3YlVGOD0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiIwZDI3ZGY3OGU2NzE0MGI2M2RmMTc1ZmU1YTM5MjE4YWU1NWMwYmJmNzZjMDgwYTFjZjJkZmI2NCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWEswMzExNCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzg0NTA3NDAwLCJpYXQiOjE3ODQ0ODgyMTksImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc4NDQ4ODIxOSwic3ViIjoiYWNjZXNzX3Rva2VuIn0.cKr9pSGI5SHQArLz8duiLRia8wzi8xxEcsjQNov_phA"

# Initialize the FyersModel instance with your client_id, access_token, and enable async mode
fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")

# Make a request to get the user profile information
response = fyers.get_profile()

# Print the response received from the Fyers API
print(response)

