"""initial

Revision ID: bca48482e055
Revises: None
Create Date: 2026-07-18 10:41:47.073461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca48482e055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metrics_referenced', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('computed_metrics',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('feature_store',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('instrument_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('underlying', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_index(op.f('ix_instruments_underlying'), 'instruments', ['underlying'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('prob_gain_10pct', sa.Float(), nullable=True),
    sa.Column('prob_gain_20pct', sa.Float(), nullable=True),
    sa.Column('prob_gain_30pct', sa.Float(), nullable=True),
    sa.Column('horizon_minutes', sa.Integer(), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('option_chain_snapshots',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('ltp', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('bid_qty', sa.BigInteger(), nullable=True),
    sa.Column('ask_qty', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('change_oi', sa.Float(), nullable=False),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.Column('intrinsic_value', sa.Float(), nullable=True),
    sa.Column('time_value', sa.Float(), nullable=True),
    sa.Column('spot_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('scoring_snapshots',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('bull_score', sa.Float(), nullable=True),
    sa.Column('bear_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('oi_score', sa.Float(), nullable=True),
    sa.Column('greeks_score', sa.Float(), nullable=True),
    sa.Column('volatility_score', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('institutional_score', sa.Float(), nullable=True),
    sa.Column('dealer_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('trade_journal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('entry_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exit_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('greeks_at_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('greeks_at_exit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores_at_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lessons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bull_score', sa.Float(), nullable=True),
    sa.Column('bear_score', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_ticks',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('ltp', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('bid_qty', sa.BigInteger(), nullable=True),
    sa.Column('ask_qty', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('change_oi', sa.Float(), nullable=False),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_ticks')
    op.drop_table('trade_signals')
    op.drop_table('trade_journal')
    op.drop_table('scoring_snapshots')
    op.drop_table('option_chain_snapshots')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_instruments_underlying'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('feature_store')
    op.drop_table('computed_metrics')
    op.drop_table('ai_reports')
    # ### end Alembic commands ###
